<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Scripts\Data\" />
    <Folder Include="Scripts\Overworld\" />
    <Folder Include="Scripts\UI\Menus\" />
    <Folder Include="planning" />
    <Folder Include="Nodes" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".gitignore" />
    <Content Include="BATTLE_INPUT_FLOW.md" />
    <Content Include="BUGS.md" />
    <Content Include="External\presentation-queue\.gitignore" />
    <Content Include="NOTES.md" />
    <Content Include="README.md" />
    <Content Include="STYLE_GUIDE.md" />
    <Content Include="TASKS.md" />
    <Content Include="planning\*" />
    <Content Include="Nodes\**\*.tscn" />
  </ItemGroup>
</Project>