<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Scripts\Battle\Controllers\" />
    <Folder Include="Scripts\Data\" />
    <Folder Include="Scripts\Overworld\" />
    <Folder Include="Scripts\UI\Menus\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="STYLE_GUIDE.md" />
  </ItemGroup>
</Project>